language: php
phps:
  - 5.3
  - 5.4
before_script:
  - git clone --quiet git://github.com/markushausammann/Zend-1.11.git Zend
  - wget http://getcomposer.org/composer.phar 
  - php composer.phar install
  - phpenv rehash
script: phpunit --configuration ./tests/phpunit.xml
notifications:
    email: markus.hausammann@cloud-solutions.net